#!/bin/bash
core=""
core="$core amd-ucode"
core="$core alacritty"
core="$core chromium"
core="$core cronie"
core="$core firefox"
core="$core git"
core="$core gvim"
core="$core htop"
core="$core man"
core="$core mpv"
core="$core neofetch"
core="$core nextcloud-client"
core="$core yakuake"
