#!/bin/bash
core=""
core="$core amd-ucode"
core="$core alacritty"
core="$core chromium"
core="$core cronie"
core="$core firefox"
core="$core git"
core="$core gvim"
core="$core gimp"
core="$core htop"
core="$core mandoc"
core="$core man-pages"
# is this where mpv belongs??
core="$core mpv"
core="$core neofetch"
core="$core nextcloud-client"
core="$core tor"
core="$core yakuake"

# file systems this might be redundant
core="$core btrfs-progs"
core="$core dosfstools"
core="$core exfatprogs"
core="$core exfat-utils"
core="$core f2fs-tools"
core="$core e2fsprogs"
core="$core jfsutils"
core="$core nilfs-utils"
core="$core ntfs-3g"
core="$core reiserfsprogs"
core="$core udftools"
core="$core xfsprogs"
core="$core sshfs"
