#!/bin/sh
gpu_drivers=""
gpu_drivers="$gpu_drivers mesa"
gpu_drivers="$gpu_drivers mesa-vdpau"
gpu_drivers="$gpu_drivers libva-mesa-driver"
gpu_drivers="$gpu_drivers vulkan-radeon"
gpu_drivers="$gpu_drivers lib32-mesa"
gpu_drivers="$gpu_drivers lib32-mesa-vdpau"
gpu_drivers="$gpu_drivers lib32-libva-mesa-driver"
gpu_drivers="$gpu_drivers lib32-vulkan-radeon"
gpu_drivers="$gpu_drivers xf86-video-amdgpu"
gpu_drivers="$gpu_drivers xf86-video-ati"
gpu_drivers="$gpu_drivers nvidia-utils"
gpu_drivers="$gpu_drivers lib32-nvidia-utils"
gpu_drivers="$gpu_drivers nvidia"
